# Routr Credentials Configuration
apiVersion: v1
kind: Collection
items:
  # Credentials for the web client peer
  - apiVersion: v1
    kind: Credentials
    metadata:
      name: web-client-credentials # A name for this credentials object
    spec:
      # The username for authentication (must match the username in peers.yaml)
      username: your-web-client-username # Replace with the username
      # The password (secret) for authentication
      password: your-web-client-password # Replace with the password

  # Optional: Credentials for the provider gateway if required for outbound calls
  # - apiVersion: v1
  #   kind: Credentials
  #   metadata:
  #     name: provider-credentials # A name for this credentials object
  #   spec:
  #     username: your-provider-username # Replace with provider username
  #     password: your-provider-password # Replace with provider password
